# Generated by Django 4.2.26 on 2025-11-17 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('ORGANIZATION', 'Organização / Grupo'), ('FACILITY', 'Unidade física (hospital, clínica)'), ('DEPARTMENT', 'Setor / Serviço'), ('UNIT', 'Unidade / Ala'), ('SUBSCALE', 'Sub-escala'), ('TEAM', 'Time'), ('CUSTOM', 'Customizado')], default='FACILITY', max_length=20)),
                ('is_schedulable', models.BooleanField(default=False, help_text='Se pode ter plantões/turnos diretamente associados a este nó.')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('conflict_scope_parent', models.ForeignKey(blank=True, help_text='Nó pai para conflito agregado (ex.: Semi + Enfermaria → Clínica Médica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_children', to='org.orgunit')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='org.orgunit')),
            ],
            options={
                'verbose_name': 'Organizational Unit',
                'verbose_name_plural': 'Organizational Units',
            },
        ),
        migrations.CreateModel(
            name='OrgUnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Membro'), ('MANAGER', 'Gerente'), ('ADMIN', 'Administrador da unidade'), ('VIEWER', 'Somente visualização')], default='MEMBER', max_length=20)),
                ('can_take_shifts', models.BooleanField(default=True, help_text='Se este usuário pode assumir plantões nesta unidade.')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Ordem opcional de prioridade base para este usuário na unidade.')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='org.orgunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('org_unit', 'user')},
            },
        ),
    ]
