# Generated by Django 4.2.26 on 2025-11-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='type',
            field=models.CharField(choices=[('ORGANIZATION', 'Organização / Grupo'), ('FACILITY', 'Unidade física (hospital, clínica)'), ('DEPARTMENT', 'Setor / Serviço'), ('UNIT', 'Unidade / Ala'), ('SUBSCALE', 'Sub-escala'), ('TEAM', 'Time'), ('CUSTOM', 'Customizado')], default='ORGANIZATION', max_length=20),
        ),
        migrations.AlterModelTable(
            name='orgunit',
            table='org_unit',
        ),
        migrations.AlterModelTable(
            name='orgunitmembership',
            table='org_unit_membership',
        ),
    ]
